services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: municipality_db
      POSTGRES_USER: municipality_user
      POSTGRES_PASSWORD: municipality_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U municipality_user -d municipality_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./municipality-service-backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/municipality_db
      SPRING_DATASOURCE_USERNAME: municipality_user
      SPRING_DATASOURCE_PASSWORD: municipality_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: "true"

      JWT_SECRET: "5cW4v2sQ9mJkT7xYpN3aL8hR6eB1uD0fGzVqKcXnI4tS7yPpH2mN8rJ6aZ1dE0uQ"
      JWT_EXPIRATIONMS: "1800000"

      SERVER_PORT: "6969"
    ports:
      - "6969:6969"

  frontend:
    build:
      context: ./municipality-service-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: "http://localhost:6969"
    ports:
      - "5173:5173"

  pgadmin:
    image: dpage/pgadmin4:8
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
